name: rails-api-heroku-stack
description: |
  This stack will generate a Rails App and setup a workflow to deploy it to Heroku
branding:
  icon: 'cloud'
  color: 'purple'

inputs:
  - name: RUBY_VERSION
    default: 3.0.2
    description: The version of ruby to use

  - name: RAILS_VERSION
    default: 6.1.4.1
    description: The version of rails to use

  - name: RAILS_RC_URL
    required: false
    description: (Optional) A URL to a .railsrc file

  - name: HEROKU_EMAIL
    description: Heroku email
    is-secret: true

  - name: HEROKU_API_KEY
    description: Heroku api key
    is-secret: true

  - name: HEROKU_APP_NAME
    description: Heroku app name

configs:
  repo-metadata:
    parameters:
      secrets: 
      - name: HEROKU_EMAIL
        value: ${{ inputs.HEROKU_EMAIL }}
      - name: HEROKU_API_KEY
        value: ${{ inputs.HEROKU_API_KEY }}
      description: "changeme" # this is required right now due to a known bug
      topics:
      - rails
      
  branches:
    - name: main
      parameters:
        enforce-admins: true
        required-pull-request-reviews:
          dismiss-stale-reviews: true
          require-code-owner-reviews: true
          required-approving-review-count: 1
        allow-force-pushes: false
        allow-deletions: false

  environments: 
    - name: heroku
      parameters: 
        protected-branches: true
        custom-branch-policies: true

  security:
    parameters: 
      vulnerability-alerts: true
      automated-security-fixes: true

init:
 uses: "stack-init.yml"
 
