name: Validate Stack
on:
  workflow_dispatch:
  pull_request:
    branches: 
    - main
  push:
    branches:
    - main
jobs:
  validate-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: sundargs2000/stacks-pre-publish@master
